# Generated by Django 4.1 on 2022-08-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='desciption',
        ),
    ]
