# Generated by Django 4.1 on 2022-08-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_recipe_desciption'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='desciption',
            field=models.TextField(blank=True),
        ),
    ]
