# Generated by Django 4.1 on 2022-08-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desciption',
            new_name='description',
        ),
    ]
